# Generated by Django 4.1.5 on 2023-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('img', models.ImageField(upload_to='img/', verbose_name='Картинка')),
                ('text', models.TextField(default=None, verbose_name='Текст')),
            ],
        ),
    ]
